name: checkpatch

on: [push, pull_request]

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y codespell
      - uses: actions/checkout@v4
        with:
          path: src
      - uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          path: linux
      - run: make KDIR="${{ github.workspace }}/linux" checkpatch
        working-directory: src
