name: checkpatch

on: [push, pull_request]

jobs:
  checkpatch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: src
      - uses: actions/checkout@v3
        with:
          repository: torvalds/linux
          path: linux
      - run: make KDIR="${{ github.workspace }}/linux" checkpatch
        working-directory: src
